version: '3.8'

services:
  nest-js-boilerplate-dev:
    container_name: nest-js-boilerplate-dev
    image: nest-js-boilerplate-dev
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - nest-js-boilerplate-mongodb # Đảm bảo mongoDB đã start thành công mới chạy container api
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    restart: unless-stopped

  nest-js-boilerplate-mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

  nest-js-boilerplate-mongo-express:
    container_name: nest-js-boilerplate-mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_USERNAME} # 2 biến này dùng làm basic
      ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_PASSWORD} # auth khi truy cập mongo_express
      ME_CONFIG_MONGODB_URL: ${DATABASE_URI}?authSource=admin # Đây là thông tin kết nối tới database
    ports:
      - 8002:8081 # Expose ra port 8002 để truy cập
    depends_on:
      - nest-js-boilerplate-mongodb
    restart: unless-stopped

networks:
  default:
    driver: bridge
